config/routes.rb
Rails.application.routes.draw do
  root to: "redirects#new"
  resources :redirects, only: [:new, :create, :index] do
    member do
      get '/update', to: "redirects#update"
    end
  end
end

app/models/branch.rb
require 'tmpdir'
require 'fileutils'

class Branch
  PREVOOM = 0
  INVOOM = 1
  POSTVOOM = 2

  def initialize
    @tmpdir = Dir.mktmpdir
  end

  def add_vanity_url(redirect)
    redirect.save!
    puts @tmpdir
    FileUtils.chdir @tmpdir
    `git clone -b voom-base ssh://git@stash.atlassian.roh.org.uk/web/server-configuration---content.git`
    t = Time.now.utc.strftime('%Y%m%dT%H%M%S')
    branch = "voom-#{t}"
    FileUtils.chdir 'server-configuration---content'
    `git checkout -b #{branch}`

    conffile = 'etc/apache2/sites-available/default.conf'
    oldconf = File.read(conffile)

    voomstart = "# ==== Managed by the Voom below ===="
    voomstop = "# ==== Managed by the Voom above ===="

    state = PREVOOM
    prevoom = ""
    postvoom = ""
    oldconf.each_line do |line|
      if state == PREVOOM
        prevoom += line
      elsif state == INVOOM
      elsif state == POSTVOOM
        postvoom += line
      end

      if line =~ /#{voomstart}/
        state = INVOOM
      elsif line =~ /#{voomstop}/
        state = POSTVOOM
      end
    end

    newconf = File.open(conffile, 'w')
    newconf.write prevoom
    Heading.order(:rank).each do |heading|
      newconf.puts "" unless heading.rank == 10
      newconf.puts "        ##{heading.title}"
      Redirect.where(heading_id: heading.id).sort do |a, b|
        a.source.downcase <=> b.source.downcase
      end.each do |redirect|
        l = redirect.source.length
        if heading.rank < 80
          padding = if l < 23 then ' ' * (23 - l) else ' ' end
        else
          padding = " "
        end
        type = redirect.type.name
        status = redirect.type.status_code
        if type == 'permanent' || type == 'temporary'
          newconf.puts "        Redirect #{status} #{redirect.source}#{padding}#{redirect.target}"
        elsif type == 'gone'
          newconf.puts "        Redirect gone #{redirect.source}"
        end
      end
    end
    newconf.write ' ' * 8 + voomstop + "\n"
    newconf.write postvoom

    # conf = File.open(conffile, 'w')
    # conf.puts "        Redirect 301 #{source}   #{target}"
    # conf.close
    system("git diff")
    `git commit -am 'Commit from the Voom.'`
    # puts `git push -u origin #{branch}`
    branch
  end
end

app/models/heading.rb
class Heading < ActiveRecord::Base
  has_many :redirects
end

app/models/redirect.rb
class Redirect < ActiveRecord::Base
  # attr_accessible :source, :target, :name, :stakeholder
  belongs_to :heading
  belongs_to :type
end

app/models/type.rb
class Type < ActiveRecord::Base
  has_many :redirects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/redirects_controller.rb
class RedirectsController < ApplicationController
  def new
    @redirect = Redirect.new
  end

  def create
    @redirect = Redirect.new(params[:redirect].permit(:source, :target, :name, :stakeholder).merge({ heading: Heading.find_by_title("added by the Voom"), type: Type.find_by_status_code(301) }))
    @already_exists = Redirect.find_by_source(@redirect.source)
    @branch_name = Branch.new.add_vanity_url(@redirect)
  end

  def index
    # Redirect.all
    @redirects = { }
    @count = 0
    Heading.order(:id).each do |heading|
      @redirects[heading] = Redirect.where(heading: heading).order(:name)
      @count += @redirects[heading].count
    end
    # @count = @redirects.inject { |sum, head, redirs| sum + redirs.count }
  end

  def update
    @redirect = Redirect.find(params[:id])
    @redirect.update!(target: params[:target])
    @branch_name = Branch.new.add_vanity_url(@redirect)
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def new
  end

  def create
    @source = params['url']['source']
    @target = params['url']['target']
    @name = params['url']['name']
    @stakeholder = params['url']['stakeholder']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
%head
  %title Voom
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body>

#main
  #topbar
    %a{title: "Royal Opera House home", href: "http://www.roh.org.uk"}
      %img{width: 64, height: 86, alt: "Royal Opera House brandmark", src: "http://roh.global.ssl.fastly.net/images/brandmark.png"}
    #title ROH Voom
  #mainbody
  = yield

app/views/redirects/_request_created.html.haml
%h1 Request created
%p Congratulations!  You’ve just created a new branch with name #{@branch_name} for the following redirection: #{@redirect.source} to #{@redirect.target}
%p
  Developers can now create a
  = link_to "pull request", "http://stash.atlassian.roh.org.uk/projects/WEB/repos/server-configuration---content/pull-requests?create&targetBranch=refs%2Fheads%2Fvoom-base&sourceBranch=refs%2Fheads%2F#{@branch_name}"

app/views/redirects/create.html.haml
- if @already_exists
  %h1 Short URL already exists
  %p
    Sorry, the short URL you’ve requested
    (#{link_to "http://www.roh.org.uk#{@redirect.source}", "http://www.roh.org.uk#{@redirect.source}"})
    already exists and points to
    #{link_to @already_exists.target, @already_exists.target}.
    Do you want to replace it with
    #{link_to @redirect.target, @redirect.target}?
    = link_to "Click here", update_redirect_path(@already_exists, target: @redirect.target)
    to confirm.
- else
  = render 'request_created'

app/views/redirects/index.html.haml
%h1 All redirects (#{@count} altogether)

- @redirects.each do |heading, redirects_by_heading|
  - if redirects_by_heading.count > 0
    %h2 #{heading.title} (#{redirects_by_heading.count})

    %table
      %thead
        %tr
          %th Source
          %th Target
      %tbody
        - redirects_by_heading.each do |redirect|
          %tr
            %td= redirect.source
            %td= link_to redirect.target, redirect.target

app/views/redirects/new.html.haml
%h1 Create short URL

%p Welcome to the Voom.

=form_for @redirect do |f|
  %p
    You want to create a redirection
    %strong from
    http://www.roh.org
    = f.text_field :source
    %strong to
    = f.text_field :target
    (for the target, type full address including ‘http://’)
  %p
    %strong Your name
    = f.text_field :name
  %p
    If applicable,
    %strong name of person who requested short URL
    = f.text_field :stakeholder

  = f.submit "Send creation request"

%p
  See
  =link_to "Current list", redirects_path
  of short URLs.

app/views/redirects/update.html.haml
= render 'request_created'